apiVersion: apps/v1
kind: Deployment
metadata:
  name: finsecure-app
  namespace: logistream
  labels:
    app: finsecure-app
    team: backend
    environment: production
    feature: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finsecure-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: finsecure-app
    spec:
      containers:
        - name: finsecure-app
          image: europe-west9-docker.pkg.dev/ynov-cloud-theo/tp2-registry/finsecure-app:v1
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "10.152.135.83"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: finsecure-app-svc
  namespace: logistream
  labels:
    app: finsecure-app
spec:
  selector:
    app: finsecure-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
