# Deployment du GPS Producer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gps-producer
  namespace: logistream  # ← CHANGER de 'kafka' à 'logistream'

spec:
  replicas: 1
  selector:
    matchLabels:
      app: gps-producer

  template:
    metadata:
      labels:
        app: gps-producer

    spec:
      containers:
        - name: gps-producer
          image: PRODUCER_IMAGE

          envFrom:
            - configMapRef:
                name: logistream-config

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

---
# Deployment du Tracker Consumer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-consumer
  namespace: logistream  # ← CHANGER de 'kafka' à 'logistream'

spec:
  replicas: 3

  selector:
    matchLabels:
      app: tracker-consumer

  template:
    metadata:
      labels:
        app: tracker-consumer

    spec:
      containers:
        - name: tracker-consumer
          image: CONSUMER_IMAGE

          envFrom:
            - configMapRef:
                name: logistream-config

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"